### ISSUE TITLE
Reset game on page load

### ISSUE THREAD

**Issue by SimonStnn** [Comon-tech/numQuest#10]
The `resetGame` function should run on the `DOMContentLoaded` event. This ensures that every game behaves the same. 

https://github.com/Comon-tech/numQuest/blob/4dfd7d57e70fecf71bc480b9027f171355d71b7c/index.js#L85-L89

This functionality should also be placed in the `resetGame` function

**Comment by C-o-m-o-n** [comment]
> The `resetGame` function should run on the `DOMContentLoaded` event. This ensures that every game behaves the same.
> 
> https://github.com/Comon-tech/numQuest/blob/4dfd7d57e70fecf71bc480b9027f171355d71b7c/index.js#L85-L89
> 
> This code section should also be placed in the `resetGame` function

Are you in a position to update that?, I'll really apreciate....
Kindly join our discord for efficient communications with the others
 https://discord.gg/RCFAKcna
