### ISSUE TITLE
Join Discord channel for efficient commuication

### ISSUE THREAD

**Issue by C-o-m-o-n** [Comon-tech/numQuest#11]
https://discord.gg/RCFAKcna

**Comment by SimonStnn** [comment]
Maybe add this to the [README.md](https://github.com/Comon-tech/numQuest/blob/3bbf9d88c29c712ed0394a9277f3304675615f3f/README.md) of the project?

**Comment by C-o-m-o-n** [comment]
> Maybe add this to the [README.md](https://github.com/Comon-tech/numQuest/blob/3bbf9d88c29c712ed0394a9277f3304675615f3f/README.md) of the project?

done
