### ISSUE TITLE
Scripts should be placed in html head

### ISSUE THREAD

**Issue by SimonStnn** [Comon-tech/numQuest#24]
The script should be placed in the head of the html file.

https://github.com/Comon-tech/numQuest/blob/0f740c2f29b5f72a468867fce3d96d65e640a5c1/index.html#L70

**Comment by C-o-m-o-n** [comment]
> The script should be placed in the head of the html file.
> 
> https://github.com/Comon-tech/numQuest/blob/0f740c2f29b5f72a468867fce3d96d65e640a5c1/index.html#L70

Why?.
Tell us on discord

**Comment by SimonStnn** [comment]
My aswer can be found [here](https://discord.com/channels/998348763489898548/998348764282634242/1184259665228472452) on discord.

> "Placing the script at in the head of a document is a common practice. This also keeps all the imports (css, scripts, etc) at the top of the document to enhance readability. This also ensures the script is ready as early as possible."

**Comment by SimonStnn** [comment]
@C-o-m-o-n I see you added the following to `index.html`. 

https://github.com/Comon-tech/numQuest/blob/70a8aa85ce24f6adda146ea07fbc51d5d269de39/index.html#L9

The `difer` attribute is not correct. It should be `defer`. Here is the correct notation:

```js
<script src="./resources/js/index.js" type="module" defer></script>
```

This will make sure the script is correctly deferred and loaded after the page has finished parsing.

**Comment by SimonStnn** [comment]
I see this is still not implemented. Any specific reason? Should I open a new pull request that fixes this issue?

**Comment by C-o-m-o-n** [comment]
> I see this is still not implemented. Any specific reason? Should I open a new pull request that fixes this issue?

yah, go ahead
