### ISSUE TITLE
Incorrect defer attribute in script tag

### ISSUE THREAD

**Issue by SimonStnn** [Comon-tech/numQuest#27]
@C-o-m-o-n I see you added the following to `index.html`. 

https://github.com/Comon-tech/numQuest/blob/70a8aa85ce24f6adda146ea07fbc51d5d269de39/index.html#L9

The `difer` attribute is not correct. It should be `defer`. Here is the correct notation:

```js
<script src="./resources/js/index.js" type="module" defer></script>
```

This will make sure the script is correctly deferred and loaded after the page has finished parsing.

> This is a followup on #24.

**Comment by C-o-m-o-n** [comment]
> @C-o-m-o-n I see you added the following to `index.html`.
> 
> https://github.com/Comon-tech/numQuest/blob/70a8aa85ce24f6adda146ea07fbc51d5d269de39/index.html#L9
> 
> The `difer` attribute is not correct. It should be `defer`. Here is the correct notation:
> 
> ```js
> <script src="./resources/js/index.js" type="module" defer></script>
> ```
> 
> This will make sure the script is correctly deferred and loaded after the page has finished parsing.
> 
> > This is a followup on #24.

OH, That must have been a typo. Sorry
