### ISSUE TITLE
Doesn't work with the latest update

### ISSUE THREAD

**Issue by LyubomirT** [Comon-tech/numQuest#29]
When trying to launch the game I notice that none of the buttons do anything, the game itself doesn't start, and nothing happens when I interact with the site anyhow. This is what I get in the console:

![image](https://github.com/Comon-tech/numQuest/assets/127299159/82b23782-9df6-475d-8088-51e77bf86361)

**Comment by SimonStnn** [comment]
@C-o-m-o-n, I see you made changes to fix this issue. There are still import issues when importing the audio in the [current deployment](https://github.com/Comon-tech/numQuest/actions/runs/7268231079). 

![image](https://github.com/Comon-tech/numQuest/assets/113850648/1f1d55c8-5d70-4be7-8134-42f46cc37473)

**Comment by C-o-m-o-n** [comment]
> @C-o-m-o-n, I see you made changes to fix this issue. There are still import issues when importing the audio in the [current deployment](https://github.com/Comon-tech/numQuest/actions/runs/7268231079).
> 
> ![image](https://private-user-images.githubusercontent.com/113850648/292503200-1f1d55c8-5d70-4be7-8134-42f46cc37473.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTQ3MDQsIm5iZiI6MTcwMzI1NDQwNCwicGF0aCI6Ii8xMTM4NTA2NDgvMjkyNTAzMjAwLTFmMWQ1NWM4LTVkNzAtNGJlNy04MTM0LTQyZjQ2Y2MzNzQ3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQxNDEzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTA0MmFjNGZiNGVlODMwZDNkZTJlNjQ0YjZhODcxOTZjMTc3ZDlhNGIwNzVhM2JiNGM4MDc5ZDIyYzhiNmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HkXCzkJ4OjvKdalQIxCS7VaiC4lkekKWGlxi6If8dyk)

I know. Ive tried to fix it but I have realized the modularized version only works when run from a server. That's why it only works on localhost and not on gh-pages. we will have to implement it in react or just return it back to the file based system. That's just my theory.

**Comment by SimonStnn** [comment]
I don't think this is the case. It is abled to load the script files and style sheets. So the issue lays somewhere else.

**Comment by C-o-m-o-n** [comment]
> I don't think this is the case. It is abled to load the script files and style sheets. So the issue lays somewhere else.

what do you suggest?

**Comment by SimonStnn** [comment]
I did some more research after [my last comment](https://github.com/Comon-tech/numQuest/issues/29#issuecomment-1867729665) and i found that the following link loads the audio: 

<https://comon-tech.github.io/numQuest/resources/audio/lady-of-the-80.mp3>

But this is the link the js is trying to load the resource from:

<https://comon-tech.github.io/resources/audio/lady-of-the-80.mp3>

I think that if we use relative importing in the `AudioPlayer` class, the js will be abled to load the resources. Now we are using absolute importing from the root.

https://github.com/Comon-tech/numQuest/blob/eff6268abc5bfe47a5024913abcb114b36e73e02/resources/js/AudioPlayer.js#L72-L88

The way we should import the audio should be `./resources/...`

**Comment by C-o-m-o-n** [comment]
> I did some more research after [my last comment](https://github.com/Comon-tech/numQuest/issues/29#issuecomment-1867729665) and i found that the following link loads the audio:
> 
> https://comon-tech.github.io/numQuest/resources/audio/lady-of-the-80.mp3
> 
> But this is the link the js is trying to load the resource from:
> 
> https://comon-tech.github.io/resources/audio/lady-of-the-80.mp3
> 
> I think that if we use relative importing in the `AudioPlayer` class, the js will be abled to load the resources. Now we are using absolute importing from the root.
> 
> https://github.com/Comon-tech/numQuest/blob/eff6268abc5bfe47a5024913abcb114b36e73e02/resources/js/AudioPlayer.js#L72-L88
> 
> The way we should import the audio should be `./resources/...`

can you kindly, try  it?

**Comment by SimonStnn** [comment]
Okey great, the music starts playing as expected.

**Comment by C-o-m-o-n** [comment]
Everything should be fixed now
