### ISSUE TITLE
Settings icon

### ISSUE THREAD

**Issue by SimonStnn** [Comon-tech/numQuest#34]
Use an icon in the settings header instead of `ICON` as text. 

https://github.com/Comon-tech/numQuest/blob/fd4be84c0edecbadd6705b0818fedce328f1eec0/index.html#L17

We can use a [Font Awesome gear icon](https://fontawesome.com/icons/gear), this is the easiest and least work. But this may not match the style of the website. 

Another option is making your own gear icon (preferably an svg, but image types like png, jpg, ... works too). This is more work to do, but by making your own icon you have full control of the looks and you can make sure it matches the website style.

**Comment by C-o-m-o-n** [comment]
> Use an icon in the settings header instead of `ICON` as text.
> 
> https://github.com/Comon-tech/numQuest/blob/fd4be84c0edecbadd6705b0818fedce328f1eec0/index.html#L17
> 
> We can use a [Font Awesome gear icon](https://fontawesome.com/icons/gear), this is the easiest and least work. But this may not match the style of the website.
> 
> Another option is making your own gear icon (preferably an svg, but image types like png, jpg, ... works too). This is more work to do, but by making your own icon you have full control of the looks and you can make sure it matches the website style.

feel free to update it

**Comment by SimonStnn** [comment]
I'll add a font awesome icon.
