### ISSUE TITLE
All code commented out

### ISSUE THREAD

**Issue by SimonStnn** [Comon-tech/numQuest#39]
@C-o-m-o-n why did you comment out all the code in [ba17a70e/resources/js/index.js](https://github.com/Comon-tech/numQuest/blame/ba17a70e5754cf36245ef4cb473e110fa716c41c/resources/js/index.js). This should be reverted, now the website is unusable.

**Comment by C-o-m-o-n** [comment]
> @C-o-m-o-n why did you comment out all the code in [ba17a70e/resources/js/index.js](https://github.com/Comon-tech/numQuest/blame/ba17a70e5754cf36245ef4cb473e110fa716c41c/resources/js/index.js). This should be reverted, now the website is unusable.

this is how I debug my code. I comment the whole code then I uncomment each function till I get the culprit.

**Comment by SimonStnn** [comment]
It is not a good practice to comment out all the code, especially committing and pushing it to the remote. Now the code is broken for everyone. 

If you do want to comment out all the code to debug it you should do it on a separate branch. This ensures the main branch keeps it's functionality.

**Comment by C-o-m-o-n** [comment]
> It is not a good practice to comment out all the code, especially committing and pushing it to the remote. Now the code is broken for everyone.
> 
> If you do want to comment out all the code to debug it you should do it on a separate branch. This ensures the main branch keeps it's functionality.

I understand. I will uncomment the code right away

**Comment by SimonStnn** [comment]
Great! Thank you.

**Comment by C-o-m-o-n** [comment]
> Great! Thank you.

I have uncommented the code,but no function is working

**Comment by C-o-m-o-n** [comment]
> > Great! Thank you.
> 
> I have uncommented the code,but no function is working

If I comment the code back, those function are working (the ones that worked before)

**Comment by SimonStnn** [comment]
I'm not sure how this is possible. I may need a more detailed explanation of what's happening. What you're saying here doesn't really make sence.

**Comment by C-o-m-o-n** [comment]
> I'm not sure how this is possible. I may need a more detailed explanation of what's happening. What you're saying here doesn't really make sence.

When I updated the filesystem to be modular, at first, some functions like the background music did not work then all the functions stopped working. So to ressolve this, I decided to comment all the functions, then uncomment them one by one as I solve them. You then solved the function for playng the bg-music, and you opened this issue. So When I uncomment the rest of the code, nothing works, even the bg-music function, but it works when I comment the rest of the code. So my suggestion is to pick one function like the "guessing" function, uncomment  and solve it, then pick another one. I hope you understand now

**Comment by SimonStnn** [comment]
Yes, you should do that. It seems this could be the best option. What you also can do is revert the commit that commented out all the code.

**Comment by C-o-m-o-n** [comment]
> Yes, you should do that. It seems this could be the best option. What you also can do is revert the commit that commented out all the code.

I have uncommented the rest of the code and fixed the functions. They are working like a charm now
