### ISSUE TITLE
Infinite score glitch after guessing correctly once

### ISSUE THREAD

**Issue by SimonStnn** [Comon-tech/numQuest#40]
After you guessed correctly the congratulations text is shown. But the guess button is still shown. If you click it again you will win again. So maybe the guess button should be made invisible after you won the game?

> Don't forget to make the button re-appear when the game starts again.

![image](https://github.com/Comon-tech/numQuest/assets/113850648/e217bfa3-2da8-4986-a67a-2e8b7a691120)

**Comment by LyubomirT** [comment]
Perhaps I can take on that issue, the function that rewards the player can simply be locked (as if in, it will not reward you if you click it again). Thank you for reporting the problem.

**Comment by LyubomirT** [comment]
Fixed in #45.
